RestaurantAutomation/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantAutomation.DataAccess.Abstract;
using RestaurantAutomation.DataAccess.Concrete;
using RestaurantAutomation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantAutomation.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository _orderRepository;
        private IProductRepository _productRepository;
        private ITableRepository _tableRepository;
        private IEmployeeRepository _employeeRepository;

        public OrderController()
        {
            _orderRepository = new OrderRepository();
            _productRepository = new ProductRepository();
            _tableRepository = new TableRepository();
            _employeeRepository = new EmployeeRepository();
        }

        public IActionResult Index()
        {
            ViewBag.orders = _orderRepository.GetOrderDtos();
            return View();
        }
        public IActionResult TableOrders(int id)
        {
            ViewBag.orders = _orderRepository.GetOrderDtosById(id);
            return View();
        }
        public IActionResult Save(Order order)
        {
            if (order.Id == 0)
            {
                this._orderRepository.Add(order);
            }
            else
            {
                this._orderRepository.Update(order);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Add(int id)
        {
            ViewBag.products = _productRepository.GetAll();
            ViewBag.tables = _tableRepository.GetAll();
            ViewBag.tableNumber = id;
            ViewBag.employees = _employeeRepository.GetAll();
            return View();
        }
        public IActionResult Update(int id)
        {
            ViewBag.tableNumber = id;
            ViewBag.products = _productRepository.GetAll();
            var order = this._orderRepository.GetById(id);
            if (order == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.orders = order;
            _orderRepository.Update(order);
            return View();
        }
        public IActionResult Delete(int id)
        {
            _orderRepository.DeleteById(id);
            return RedirectToAction("Index");
        }

    }
}

RestaurantAutomation/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantAutomation.DataAccess.Abstract;
using RestaurantAutomation.DataAccess.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RestaurantAutomation.Controllers
{
    public class TableController : Controller
    {
        private ITableRepository _tableRepository;

        public TableController()
        {
            _tableRepository = new TableRepository();
        }

        public IActionResult Index()
        {
            ViewBag.tables = _tableRepository.GetAll();
            return View();
        }
    }
}

RestaurantAutomation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantAutomation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantAutomation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Index">Tables</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RestaurantAutomation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>